### ISSUE TITLE
Feature: Pre-select item index in Select Widget

### ISSUE THREAD

**Issue by flamewave000** [Exahilosys/survey#25]
It would be really nice to be able to provide an index to the item in a list that I would like to be selected by default. Similar to how the Bucket allows a list of indices for pre-selection. I have the user select a single option, but in order for the one I want as default to be auto-selected by just hitting enter, I have to do specialized sorting to get the option to the top of the list.

**Comment by Exahilosys** [comment]
Hello! You can already do this by passing `index = ...` to any BaseList widget to pre-place the cursor on an item:

```py
import survey
values = tuple(map(str, range(10)))
survey.routines.select(values = options, index = 4)
survey.routines.basket(values = options, index = 4)
```

Both of the above pre-place the cursor on the 5th element.

Feel free to close this if it satisfies your inquiry 😊

**Comment by flamewave000** [comment]
Oh excellent, it wasn't in the docs or the code doc-comments so I didn't think it was possible.

Maybe this ticket can instead be a request to update the docs for select with the available parameters?

**Comment by Exahilosys** [comment]
Glad I could help! 

The docs for the [select routine](https://survey.readthedocs.io/reference.html#survey.routines.select) mention that it uses the [Select widget](https://survey.readthedocs.io/reference.html#survey.widgets.Select) and that all "other widget and [start()](https://survey.readthedocs.io/reference.html#survey.widgets.start) arguments are valid". The widget inherits the arguments of its [BaseList parent](https://survey.readthedocs.io/reference.html#survey.widgets.BaseList) (unless otherwise specified), including [index](https://survey.readthedocs.io/reference.html#survey.widgets.BaseList.params.index).

I understand that chasing down arguments like this is not exactly ideal, but the debt of having to change the same piece of documentation in more than one place would be unsustainable for me and could quickly lead to inconsistencies.

If this resolves your issue, feel free to close!

**Comment by flamewave000** [comment]
ok, I'm unfamiliar with this style of auto-documentation. It's good to know that I need to look through the inheritance tree to determine what all of the allowable arguments are.
